name: Deploy to Nekoweb
description: Deploy to Nekoweb using the Nekoweb API
author: fairfruit
inputs: 
  API_KEY:
    description: API key for Nekoweb
    required: true
  BUILD_DIR:
    description: Local build directory to deploy
    required: true
    default: /build
  DEPLOY_DIR:
    description: Remote directory to deploy to
    required: true
    default: /
  DELAY:
    description: Delay between Nekoweb API requests (in seconds)
    default: "0.1"
  CLEANUP:
    description: Also delete remote files that don't exist locally
    default: "False"
branding:
  icon: upload-cloud
  color: blue
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: python -m pip install requests
      shell: bash

    - name: Cleanup and deploy
      run: python ${{ github.action_path }}/deploy.py ${{ inputs.API_KEY }} ${{ inputs.BUILD_DIR }} ${{ inputs.DEPLOY_DIR }} ${{ inputs.CLEANUP }}
      shell: bash
