name: Deploy to Nekoweb
description: Deploy to Nekoweb using the Nekoweb API
author: fairfruit
inputs: 
  API_KEY:
    description: Nekoweb API key
    required: true
  BUILD_DIR:
    description: Local build directory to deploy
    required: true
    default: /build
  DEPLOY_DIR:
    description: Remote directory to deploy to
    required: true
    default: /
  CLEANUP:
    description: Also delete remote files that don't exist locally
    default: "False"
branding:
  icon: upload-cloud
  color: blue
runs:
  using: "composite"
  steps:
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{ inputs.BUILD_DIR }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cleanup and deploy
      run: python deploy.py ${{ inputs.API_KEY }} ${{ inputs.BUILD_DIR }} ${{ inputs.DEPLOY_DIR }} ${{ inputs.CLEANUP }}
      shell: bash
